# Generated by Django 2.1 on 2018-08-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('NE', 'Новость'), ('NO', 'Объявление')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
