# Generated by Django 2.1 on 2018-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('NE', 'Новость'), ('NO', 'Объявление')], max_length=2, verbose_name='Тип материала'),
        ),
    ]
