# Generated by Django 2.1 on 2018-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180830_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seodescr',
            field=models.TextField(default='', help_text='SEO', max_length=250, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='seokey',
            field=models.TextField(default='', help_text='SEO', max_length=150, verbose_name='Ключевые слова'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, upload_to='', verbose_name='Картинка для новости'),
        ),
    ]
