# Generated by Django 2.1 on 2018-08-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Название и логотип', 'verbose_name_plural': 'Названия и логотипы'},
        ),
    ]
