# Generated by Django 2.1 on 2018-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20180830_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='logoBW',
            field=models.FileField(default='', upload_to='', verbose_name='Черно-белый для белого фона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='logoMobile',
            field=models.FileField(default='', upload_to='', verbose_name='Логотип для маленьких экранов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='logoMore',
            field=models.FileField(default='', upload_to='', verbose_name='Дополнительный'),
            preserve_default=False,
        ),
    ]
