# Generated by Django 2.1 on 2018-09-08 13:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20180830_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='bg',
            field=models.FileField(default='', upload_to='', verbose_name='Картинка фона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='bgColor',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Цвет фона'),
        ),
    ]
