# Generated by Django 2.1 on 2018-08-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='btnText',
            field=models.CharField(default='', max_length=50, verbose_name='Текст кнопки'),
            preserve_default=False,
        ),
    ]
