# Generated by Django 2.1 on 2018-08-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hero_btntext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Промо экран', 'verbose_name_plural': 'Промо экраны'},
        ),
    ]
