# Generated by Django 2.1 on 2018-08-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180829_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingblocks',
            options={'verbose_name': 'Промо блок', 'verbose_name_plural': 'Промо блоки'},
        ),
    ]
