# Generated by Django 2.1 on 2018-08-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180830_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingblocks',
            name='text',
        ),
    ]
