# Generated by Django 2.1 on 2018-08-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_landingblocks_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingblocks',
            name='linkText',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
