# Generated by Django 2.1 on 2018-08-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Город')),
                ('latitude', models.CharField(max_length=200, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=200, verbose_name='Долгота')),
                ('home', models.CharField(choices=[('OF', 'Офис компании Аврора'), ('HO', 'Объекты')], max_length=2)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
