# Generated by Django 2.1 on 2018-08-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='address',
            name='home',
            field=models.CharField(choices=[('OF', 'Офис компании Аврора'), ('HO', 'Объект')], max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.CharField(help_text='Брать значение с Яндекс карт', max_length=200, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.CharField(help_text='Брать значение с Яндекс карт', max_length=200, verbose_name='Долгота'),
        ),
    ]
